[package]
name = "adb-cli"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
adb-rs = { path = "../adb-rs" }
clap = { version = "3.1.12", features = ["yaml"] }
pretty-hex = "0.3.0"
simplelog = "0.12.0"
log = "0.4.16"
